# https://docs.github.com/actions

name: Lint Code Base

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Code Base
    uses: LeoColomb/.github/.github/workflows/lint.yml@main
